apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-api
  namespace: hypertheory
spec:
  selector:
    matchLabels:
      app: appointments-api
  template:
    metadata:
      labels:
        app: appointments-api
    spec:
      containers:
      - name: appointments-api
        image: appointments-api:v1.0

        ports:
        - containerPort: 80
        env:
          - name: ConnectionStrings__appointments
            value: server=mssql-service;database=appointments;user=sa;password=TokyoJoe138!

