apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: hypertheory
spec:
  clusterIP: None # "Headless - just gives the IP of the Pod running Sql Server"
  selector:
    app: mssql
  ports:
    - port: 1433
      targetPort: 1433